//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaoUpFind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 刊登協尋
    {
        public int 協尋編號 { get; set; }
        public string 協尋單號 { get; set; }
        public Nullable<int> 寵物編號 { get; set; }
        public string 協尋狀態 { get; set; }
        public Nullable<int> 會員編號 { get; set; }
        public string 會員暱稱 { get; set; }
        public string 會員電話 { get; set; }
        public Nullable<int> 走失地點_市 { get; set; }
        public Nullable<int> 走失地點_區 { get; set; }
        public string 走失地點_全 { get; set; }
        public string 備註 { get; set; }
        public string 是否結案 { get; set; }
        public Nullable<System.DateTime> 建立時間 { get; set; }
        public Nullable<System.DateTime> 更新時間 { get; set; }
        public string 協尋標題 { get; set; }
        public Nullable<System.DateTime> 走失時間 { get; set; }
    }
}
