//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaoUpFind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 城市
    {
        public int 城市編號 { get; set; }
        public string 城市名稱 { get; set; }
        public string 備註 { get; set; }
        public string 是否啟用 { get; set; }
    }
}
