//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaoUpFind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 會員違規紀錄
    {
        public int 違規紀錄編號 { get; set; }
        public Nullable<int> 留言編號 { get; set; }
        public Nullable<int> 違規行為編號 { get; set; }
        public Nullable<System.DateTime> 違規時間 { get; set; }
        public Nullable<System.DateTime> 懲罰結束時間 { get; set; }
        public string 備註 { get; set; }
        public string 是否成立 { get; set; }
    }
}
