//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaoUpFind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 通報資料
    {
        public int 通報編號 { get; set; }
        public string 通報單號 { get; set; }
        public Nullable<int> 會員編號 { get; set; }
        public string 會員暱稱 { get; set; }
        public string 會員電話 { get; set; }
        public string 通報標題 { get; set; }
        public string 狀況概述 { get; set; }
        public Nullable<System.DateTime> 通報時間 { get; set; }
        public Nullable<int> 通報地點_市 { get; set; }
        public Nullable<int> 通報地點_區 { get; set; }
        public string 發生地點_全 { get; set; }
        public Nullable<int> 急迫性編號 { get; set; }
        public string 附件一 { get; set; }
        public string 附件二 { get; set; }
        public string 附件三 { get; set; }
        public string 是否結案 { get; set; }
        public Nullable<System.DateTime> 建立時間 { get; set; }
        public Nullable<System.DateTime> 更新時間 { get; set; }
    }
}
