//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaoUpFind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 醫院會員資料
    {
        public int 編號 { get; set; }
        public Nullable<int> 會員編號 { get; set; }
        public string 醫院名字 { get; set; }
        public string 醫院電話 { get; set; }
        public string 醫院信箱 { get; set; }
        public string 聯絡人 { get; set; }
        public Nullable<int> 所在地點_市 { get; set; }
        public Nullable<int> 所在地點_區 { get; set; }
        public string 所在地點_全 { get; set; }
        public string 備註 { get; set; }
        public string 營業時間 { get; set; }
    }
}
